# docker-compose.iran-secure.yml
version: '3.8'
services:
  secure-api:
    build:
      context: .
      dockerfile: Dockerfile.secure
    environment:
      - IRAN_DEPLOYMENT=true
      - LICENSE_VALIDATION=true
      - HARDWARE_BINDING=true
      - PROXY_ROTATION_ENABLED=true
    ports:
      - "8443:8443"
    volumes:
      - ./license-keys:/app/license-keys:ro
      - ./security-configs:/app/config:ro
    networks:
      - secure-net

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=https://localhost:8443
      - VITE_LICENSE_REQUIRED=true
    ports:
      - "443:443"
    networks:
      - secure-net

networks:
  secure-net:
    driver: bridge
