# monitoring/prometheus.yml
global:
  scrape_interval: 30s  # Longer interval for Iran
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'iran-services'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080', 'proxy-manager:8081']
    
  - job_name: 'iran-network'
    scrape_interval: 60s  # Network metrics less frequently
    static_configs:
      - targets: ['network-monitor:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alerts/connectivity-alerts.yml"
  - "alerts/sanctions-alerts.yml"
