name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Go Backend Tests
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build Go services
        run: |
          cd intelligence-engine
          go build ./...
          
      - name: Run Go tests
        run: |
          cd intelligence-engine
          go test ./... -v

  # Node.js Browser Workers Tests
  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: services/browser-workers/package-lock.json
          
      - name: Install dependencies
        run: |
          cd services/browser-workers
          npm ci
          
      - name: Run Node.js tests
        run: |
          cd services/browser-workers
          npm test

  # Python AI Engine Tests
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          cd services/ai-engine
          pip install -r requirements.txt
          
      - name: Run Python tests
        run: |
          cd services/ai-engine
          python -m pytest tests/ -v

  # React UI Tests
  react-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
          
      - name: Install UI dependencies
        run: |
          cd ui
          npm ci
          
      - name: Run UI tests
        run: |
          cd ui
          npm run test:ci
          
      - name: Build UI
        run: |
          cd ui
          npm run build

  # Security Scan
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run security audit
        run: |
          cd services/browser-workers
          npm audit --audit-level moderate
          
      - name: Go security check
        run: |
          cd intelligence-engine
          go vet ./...

  # Docker Build Test
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker images
        run: |
          docker build -t osintiran/api-gateway -f services/api-gateway/Dockerfile .
          docker build -t osintiran/browser-worker -f services/browser-workers/Dockerfile .
          docker build -t osintiran/ai-engine -f services/ai-engine/Dockerfile .
