name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Cache Go dependencies - API Gateway
        uses: actions/cache@v3
        with:
          path: services/api-gateway/go/pkg/mod
          key: ${{ runner.os }}-go-apigateway-${{ hashFiles('services/api-gateway/dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-go-apigateway-
            
      - name: Cache Go dependencies - Orchestrator
        uses: actions/cache@v3
        with:
          path: services/orchestrator/go/pkg/mod
          key: ${{ runner.os }}-go-orchestrator-${{ hashFiles('services/orchestrator/dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-go-orchestrator-
            
      - name: Cache Go dependencies - Intelligence Engine
        uses: actions/cache@v3
        with:
          path: intelligence-engine/go/pkg/mod
          key: ${{ runner.os }}-go-intelengine-${{ hashFiles('intelligence-engine/dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-go-intelengine-
          
      - name: Build and Test API Gateway
        run: |
          cd services/api-gateway
          go mod download
          go build -v .
          go test -v ./...
          
      - name: Build and Test Orchestrator
        run: |
          cd services/orchestrator
          go mod download
          go build -v .
          go test -v ./...
          
      - name: Build and Test Intelligence Engine
        run: |
          cd intelligence-engine
          go mod download
          go build -v .
          go test -v ./...

  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('services/ai-engine/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-
          
      - name: Install Python dependencies
        run: |
          cd services/ai-engine
          pip install -r requirements.txt
          
      - name: Run Python tests
        run: |
          cd services/ai-engine
          python -m pytest tests/ -v

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker images
        run: |
          docker build -t osintiran/api-gateway -f services/api-gateway/Dockerfile .
          docker build -t osintiran/orchestrator -f services/orchestrator/Dockerfile .
          docker build -t osintiran/ai-engine -f services/ai-engine/Dockerfile .
