- name: Build and Test API Gateway
  run: |
    if [ -f "services/api-gateway/go.mod" ]; then
      cd services/api-gateway
      go mod download
      go build -v .
      go test -v ./...
    else
      echo "API Gateway go.mod not found, skipping..."
    fi
    
- name: Build and Test Orchestrator
  run: |
    if [ -f "services/orchestrator/go.mod" ]; then
      cd services/orchestrator
      go mod download
      go build -v .
      go test -v ./...
    else
      echo "Orchestrator go.mod not found, skipping..."
    fi
    
- name: Build and Test Intelligence Engine
  run: |
    if [ -f "intelligence-engine/go.mod" ]; then
      cd intelligence-engine
      go mod download
      go build -v .
      go test -v ./...
    else
      echo "Intelligence Engine go.mod not found, skipping..."
    fi
