# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run tests
        run: make test
        
      - name: Build containers
        run: make build
        
      - name: Deploy to production
        run: make deploy-prod
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
