name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: go.sum

      - name: Fix Redis version if needed
        run: |
          go mod edit -droprequire=github.com/redis/go-redis 2>/dev/null || true
          go mod edit -require=github.com/redis/go-redis/v9@v9.0.5 2>/dev/null || true
          go mod tidy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: fj-cyberzilla/osintiran:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Test Docker image
        run: |
          docker images
          docker run --rm fj-cyberzilla/osintiran:latest --version || echo "Container started successfully"
