name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  security-events: write
  contents: read

jobs:
  codeql-analysis:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go, python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  go-security:
    name: Go Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Go security checks
        run: |
          echo "Checking API Gateway..."
          if [ -f "services/api-gateway/go.mod" ]; then
            cd services/api-gateway
            go mod download
            go vet ./...
            go mod verify
          else
            echo "API Gateway go.mod not found, skipping..."
          fi
          
          echo "Checking Orchestrator..."
          if [ -f "services/orchestrator/go.mod" ]; then
            cd ../orchestrator
            go mod download
            go vet ./...
            go mod verify
          else
            echo "Orchestrator go.mod not found, skipping..."
          fi
          
          echo "Checking Intelligence Engine..."
          if [ -f "intelligence-engine/go.mod" ]; then
            cd ../../intelligence-engine
            go mod download
            go vet ./...
            go mod verify
          else
            echo "Intelligence Engine go.mod not found, skipping..."
          fi

      - name: Run Trivy Go scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-go.sarif'

      - name: Upload Go security results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-go.sarif'

  python-security:
    name: Python Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          if [ -f "services/ai-engine/requirements.txt" ]; then
            cd services/ai-engine
            pip install -r requirements.txt
          else
            echo "AI Engine requirements.txt not found, skipping..."
          fi

      - name: Run Trivy Python scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './services/ai-engine'
          format: 'sarif'
          output: 'trivy-python.sarif'

      - name: Upload Python security results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-python.sarif'
